apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentry-health-deployment
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1 
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: sentry-health
        # Assuming Dockerhub container registry
        image: calvinedwards/sentryhealth:1.0.0
        ports:
        - containerPort: 80